### ISSUE TITLE
Instructions to create apicGatewayServiceTLSSecret

### ISSUE THREAD

**Issue by ozairs** [ibm-apiconnect/charts#1]
You need to create a kubernetes secret (`kubectl create secret generic gw-cert --from-file=.`) and reference the name of the secret in the parameter datapower.apicGatewayTLSSecret.

```
peering_key.pem
gwd_ca.pem       
gwd_cert.pem
gwd_key.pem      
peering_cert.pem
```

You can use the `openssl` command to create key / cert pair.

**Comment by stormbard** [comment]
@ozairs I've added the following text to the README.


## Prerequisites
Before you can install this chart you need to create a kubernetes secret containing 5 certificates. These certificates can be created using `openssl`. You can create the secret using the following command `kubectl create secret generic gw-certs --from-file=.`, where `gw-certs` is the name of the secret and the from-file is current directory. The name `gw-certs` needs to be set for the required field `datapower.apicGatewayTLSSecret`. The directory needs to contains the files named below.
```
peering_key.pem
gwd_ca.pem       
gwd_cert.pem
gwd_key.pem      
peering_cert.pem
```

**Comment by stormbard** [comment]
Closing since this is now in `master`. Reopen if necessary.
